server:
  port: 8080

spring:
  application:
    name: authenticationService
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

  datasource:
    url: jdbc:mysql://172.19.160.1:3306/account-microservice
    username: root
    password: P@ss4%mysql%
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
zuul:
  routes:
    product:
      url: http://172.19.160.1:8082
    order:
      url: http://172.19.160.1:8084
    payPal:
      url: http://172.19.160.1:8091
    bank:
      url: http://172.19.160.1:8092
ribbon:
  eureka:
    enabled: true
    
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://172.19.160.1:8761/eureka}
  instance:
    preferIpAddress: true
