server:
  port: 8080

spring:
  application:
    name: authenticationService
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/account-microservice
    username: root
    password: 12345
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
