server:
  port: 8092

spring:
  application:
    name: bankService
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          

activemq:
  broker:
    url: tcp://172.19.141.91:61616
   
