server:
  port: 8092

spring:
  application:
    name: bankService
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          

activemq:
  broker:
    url: tcp://localhost:61616
