server:
  port: 8084

spring:
  application:
    name: orderService
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/order-microservice
    username: root
    password: P@ss4%mysql%
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


activemq:
  broker:
    url: tcp://172.19.160.1:61616


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://172.19.160.1:8761/eureka}
  instance:
    preferIpAddress: true
