server:
  port: 8091

spring:
  application:
    name: payPalService
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          

activemq:
  broker:
    url: tcp://172.19.160.1:61616
    

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://172.19.160.1:8761/eureka}
  instance:
    preferIpAddress: true
